<a href="https://colab.research.google.com/github/ishitarakchhit/Machine-Learning/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy Library**

In [ ]:
import numpy as np

In [ ]:
#to form an array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#to check the data type
type(arr)

numpy.ndarray

In [ ]:
#to square every element of array
arr**2

array([ 1,  4,  9, 16, 25])

In [ ]:
#to multipy every element by 10
arr*10

array([10, 20, 30, 40, 50])

In [ ]:
#to find length of array
len(arr)

5

In [ ]:
#to find the diemensions of array
arr.ndim

1

In [ ]:
#to find the no. of elements in every dimension or no. of rows and columns
arr.shape

(5,)

In [ ]:
#to create an array within given range (range start, range end-1)
arr = np.arange(10, 18)
#to create an array within given range and definite step size (range start, range end-1, step size)
arr1 = np.arange(10, 18, 2)

print(arr, arr1)

[10 11 12 13 14 15 16 17] [10 12 14 16]
[10 12 14 16]


### **Slicing**

In [ ]:
#returns element at index 1 and last
arr[[1, -1]]

array([11, 17])

In [ ]:
# returns element from index 1 to 3
arr[1:4]

array([11, 12, 13])

In [ ]:
# reverses the string
arr[::-1]

array([17, 16, 15, 14, 13, 12, 11, 10])



### **Boolean Indexing**

In [ ]:
#returns array with boolean elements when compared to 15
m1<15

array([ True,  True,  True,  True,  True, False, False, False])

In [ ]:
# masking: prints all elements less than 15
mask = m1<15
m1[mask]

array([10, 11, 12, 13, 14])

In [ ]:
#returns 10 random elemnts from 1 to 20 (excluded)
m2 = np.random.randint(1, 20, 10)
print(m2)

[ 2 12 13  7 11  2  2  2 12 18]


### **Some operations on array**

In [ ]:
#to add two arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a+b

array([ 7,  9, 11, 13, 15])

In [ ]:
#to find max of array
np.max(a)
# to find min of array
np.min(a)
#to find average of array
np.average(a)

3.0

In [ ]:
# creates a matrix of 2d array
mat = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
mat.ndim

mat.shape

#returns count of all elemnts in the matrix
mat.size

#returns size of first array
len(mat)

3

### **NPM Case Study**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving survey.txt to survey.txt


In [ ]:
scores = np.loadtxt('survey.txt', dtype='int')

In [ ]:
promotors = scores[scores>=9]
detractors = scores[scores<=6]

In [ ]:
NPS = 100*(len(promotors) - len(detractors))/ scores.size

In [ ]:
round(NPS, 1)

23.7

Conclusion: Not very good NPS hence...


## **Pandas Library**


In [ ]:
# Library for manipulation and analysis
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv


In [ ]:
titanic = pd.read_csv('titanic.csv')

In [ ]:
type(titanic)

pandas.core.frame.DataFrame

In [ ]:
titanic.shape

(891, 12)

In [ ]:
#to return defined number of rows from start, default: 5
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [ ]:
# gives all rows with column name survived
titanic['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
# returns unique elements in an array
titanic['Survived'].unique()

array([0, 1])

In [ ]:
#returns count of unique elements
titanic['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

Analysis: over 50% people died

In [ ]:
# returns in fraction
titanic['Survived'].value_counts(normalize=True)

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [ ]:
#returns mean value of column age
titanic['Age'].mean()

29.69911764705882

In [ ]:
# returns heading of all columns
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
# returns datatype of all columns
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
#returns count of all NaN values columnwise
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# same as isna
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
titanic[titanic['Survived'] == 0]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S  
4      male  35.0      0      0           373450   8.0500   NaN        S  
5      male   NaN      0      0           330877   8.4583   NaN        Q  
6      male  54.0      0      0            17463  51.8625   E46        S  
7      male   2.0      3      1           349909  21.0750   NaN        S  
..      ...   ...    ...    ...              ...      ...   ...      ...  
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5           382652  29.1250   NaN        Q  
886    male  27.0      0      0           211536  13.0000   NaN        S  
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0           370376   7.7500   NaN        Q  

[549 rows x 12 columns]

In [ ]:
titanic[titanic['Survived'] == 0]['Age'].mean()


30.62617924528302

In [ ]:
survived_data = titanic[titanic['Survived']== 1]

In [ ]:
survived_data['Sex'].value_counts(normalize=True)

female    0.681287
male      0.318713
Name: Sex, dtype: float64

In [ ]:
died_data = titanic[titanic['Survived']== 0]

In [ ]:
#to drop unwanted columns
titanic= titanic.drop(columns = ['Parch', 'Cabin', 'Embarked', 'PassengerId', 'Pclass', 'Name', 'Ticket', 'Fare'])
titanic.head()

Survived     Sex   Age  SibSp
0         0    male  22.0      1
1         1  female  38.0      1
2         1  female  26.0      0
3         1  female  35.0      1
4         0    male  35.0      0

Data Preprocessing

In [ ]:
titanic.isna().sum()

Survived      0
Sex           0
Age         177
SibSp         0
dtype: int64

In [ ]:
titanic['Age'].mean()

29.69911764705882

In [ ]:
#filling the mean value in place of missing values
titanic['Age'] = titanic['Age'].fillna(29.6)